import {
  cv,
  cv2,
  xova,
  bucyn,
  eletter1,
  eletter2,
  eletter3,
  face,
  face1,
  face2,
  ajining,
  ajining2,
  ajining3,
  cone1,
  cone2,
  cone3,
  cone4,
  cone5,
  daily1,
  daily2,
  daily3,
  diusahain1,
  diusahain2,
  diusahain3,
  jeta,
  jeta1,
  jeta2,
  jeta3,
  jeta4,
  jeta5,
  percent1,
  percent2,
  percent3,
  percent4,
  plantopia1,
  plantopia2,
  plantopia3,
  plantopia4,
  mediosa,
  mediosa4,
  mediosa1,
  mediosa2,
  mediosa3,
  meta,
  shopify,
  starbucks,
  tesla,
  itconvert,
  pkm,
  pekanit,
  nwdc,
  ftj,
  nbpc,
  fesmaro,
  katalog1,
  katalog2,
  katalog3,
  handy,
  glukofit,
  glukofit2,
} from "../assets/images";
import { flutter, contact, express, git, github, linkedin, docker, nextjs, nodejs, react, tailwindcss, typescript, linux, flask, figma, appwrite, firebase, laravel } from "../assets/icons";

export const skills = [
  {
    imageUrl: flutter,
    name: "Flutter",
    type: "Frontend",
  },
  {
    imageUrl: figma,
    name: "JavaScript",
    type: "Frontend",
  },

  {
    imageUrl: nextjs,
    name: "Next.js",
    type: "Frontend",
  },
  {
    imageUrl: laravel,
    name: "laravel",
    type: "Backend",
  },
  {
    imageUrl: nodejs,
    name: "Node.js",
    type: "Backend",
  },
  {
    imageUrl: react,
    name: "React",
    type: "Frontend",
  },
  {
    imageUrl: express,
    name: "Express",
    type: "Backend",
  },
  {
    imageUrl: flask,
    name: "HTML",
    type: "Frontend",
  },
  {
    imageUrl: firebase,
    name: "firebase",
    type: "State Management",
  },
  {
    imageUrl: appwrite,
    name: "appwrite",
    type: "Frontend",
  },
  {
    imageUrl: git,
    name: "Git",
    type: "Version Control",
  },
  {
    imageUrl: github,
    name: "GitHub",
    type: "Version Control",
  },

  {
    imageUrl: linux,
    name: "linux",
    type: "Animation",
  },
  {
    imageUrl: docker,
    name: "Material-UI",
    type: "Frontend",
  },

  {
    imageUrl: tailwindcss,
    name: "Tailwind CSS",
    type: "Frontend",
  },
  {
    imageUrl: typescript,
    name: "TypeScript",
    type: "Frontend",
  },
];

export const experiences = [
  {
    title: "2rd Place in Game & Software Development Competition",
    company_name: "FESMARO 2025, University of Malang (UM)",
    icon: starbucks,
    iconBg: "#64748b",
    image: fesmaro,
    date: "21 Apr 2024",
    points: ["Developing and maintaining web applications using React.js and other related technologies."],
  },
  {
    title: "3rd Place in Software Development Competition",
    company_name: "ITConvert, University of Jember (UNEJ)",
    icon: starbucks,
    iconBg: "#c026d3",
    image: itconvert,
    date: "28 Sept 2024",
    points: ["Developing and maintaining web applications using React.js and other related technologies."],
  },
  {
    title: "2nd Place in Software Development Competition",
    company_name: "PekanIT (UNSIKA) 2024",
    icon: tesla,
    image: pekanit,
    iconBg: "#ef4444",
    date: "21 July 2024",
    points: ["Developing and maintaining web applications using React.js and other related technologies."],
  },
  {
    title: "2nd Place in NBPC 2024",
    company_name: "Pusat Kewirausahaan LPPI UNISNU",
    icon: tesla,
    image: nbpc,
    iconBg: "#facc15",
    date: "08 August 2024",
    points: ["Developing and maintaining web applications using React.js and other related technologies."],
  },
  {
    title: "Secured Funding from PKM -KC",
    company_name: "Kemendikbud RI",
    icon: shopify,
    image: pkm,
    iconBg: "#14b8a6",
    date: "March - Aug 2024",
    points: ["Developing and maintaining web applications using React.js and other related technologies."],
  },
  {
    title: "1st Place in Web Programming Competition",
    company_name: "Festival Teknologi Jateng 2023",
    icon: meta,
    image: ftj,
    iconBg: "#3b82f6",
    date: "November 2023",
    points: ["Developing and maintaining web applications using React.js and other related technologies."],
  },
  {
    title: "1st Place in Web Design Competition",
    company_name: "Nastional Web Design Competition 2023 HMPSIF",
    icon: meta,
    image: nwdc,
    iconBg: "#C0C0C0",
    date: "November 2023",
    points: ["Developing and maintaining web applications using React.js and other related technologies."],
  },
];

export const socialLinks = [
  {
    name: "Contact",
    iconUrl: contact,
    link: "https://wa.me/62895415005347",
  },
  {
    name: "GitHub",
    iconUrl: github,
    link: "https://github.com/zuwhi",
  },
  {
    name: "LinkedIn",
    iconUrl: linkedin,
    link: "https://www.linkedin.com/in/reihan-saputra-498274282/",
  },
];

export const projects = [
  {
    name: "Pre Rolled Cones",
    description: "An application to view finished furniture products, developed using Flutter and Appwrite.",
    link: "https://prerolledconesfactory.com/",
    images: [cone1, cone2, cone3, cone4, cone5],
  },
  {
    name: "Bucyn App",
    description: "An application to view finished furniture products, developed using Flutter and Appwrite.",
    link: "https://bucyn.com",
    images: [bucyn],
  },
  {
    name: "90 Ten Percent",
    description: "An application to view finished furniture products, developed using Flutter and Appwrite.",
    link: "https://90tenpercent.com",
    images: [percent1, percent2, percent3, percent4],
  },
  {
    name: "Glukofit",
    description: "Is a mobile app that uses AI to prevent diabetes by scanning food for Nutrition, monitoring kalories, and providing health tips. Developed using Flutter with state management GetX, Appwrite, Express, Flask.",
    link: "https://s.id/glukofit",
    images: [glukofit, glukofit2],
  },
  {
    name: "Mediosa",
    description: "Website application to provide information and diagnose diseases based on symptom input using decision tree algorithm. developed using Laravel.",
    link: "https://www.youtube.com/watch?v=9Lhe_8-aGUs",
    images: [mediosa, mediosa4, mediosa1, mediosa2, mediosa3],
  },
  {
    name: "XOVA APP",
    description: "An application to view finished furniture products, developed using Flutter and Appwrite.",
    link: "",
    images: [xova],
  },
  {
    name: "Daily Cash",
    description: "An application to view finished furniture products, developed using Flutter and Appwrite.",
    link: "https://daily-cash.vercel.app/",
    images: [daily1, daily2, daily3],
  },
  {
    name: "Ajining Furniture",
    description: "An application to view finished furniture products, developed using Flutter and Appwrite.",
    link: "https://ajining.vercel.app",
    images: [ajining, ajining2, ajining3],
  },
  {
    name: "CV AI Builder",
    description: "An application to view finished furniture products, developed using Flutter and Appwrite.",
    link: "https://radiwara.my.id",
    images: [cv, cv2],
  },
  {
    name: "Diusahain.com",
    description: "An application to view finished furniture products, developed using Flutter and Appwrite.",
    link: "https://diusahain.com",
    images: [diusahain1, diusahain2, diusahain3],
  },
  {
    name: "E-Katalog Mebel",
    description: "An application to view finished furniture products, developed using Flutter and Appwrite.",
    link: "https://drive.google.com/drive/folders/1ahlnhrUYwhoamd-RELaT9Lt2JQywINKY",
    images: [katalog1, katalog2, katalog3],
  },
  {
    name: "HandyLang App",
    description: "Is a mobile app that uses AI to prevent diabetes by scanning food for Nutrition, monitoring kalories, and providing health tips. Developed using Flutter with state management GetX, Appwrite, Express, Flask.",
    link: "https://s.id/glukofit",
    images: [handy],
  },

  {
    name: "Plantopia (MSIB batch 6)",
    description: "A mobile application focused on agriculture to assist farmers with their farming activities. Developed using Flutter and Firebase.",
    link: "",
    images: [plantopia1, plantopia2, plantopia3, plantopia4],
  },
  {
    name: "Jepara E-Transport Application (JETA) ",
    description: "Website application for real-time public transportation tracking. developed using Next.js, WebSocket, and Flask",
    link: "https://www.instagram.com/jeta.app/",
    images: [jeta, jeta1, jeta2, jeta3, jeta4, jeta5],
  },

  {
    name: "E-Letter",
    description: "Website application for quickly generating automated letters using provided templates. developed using React Js.",
    link: "https://e-letter.vercel.app/",
    images: [eletter1, eletter2, eletter3],
  },
  {
    name: "Face Mask Detection",
    description: "just website for detect age and face mask using machine learning. developed using React Js.",
    link: "https://fst-facedetection.vercel.app/",
    images: [face, face1, face2],
  },
];
